//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS2ServerPicker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CS2ServerPicker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CS2 Server Picker.
        /// </summary>
        internal static string About_AppName {
            get {
                return ResourceManager.GetString("About_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by sorinalex21.
        /// </summary>
        internal static string About_Author {
            get {
                return ResourceManager.GetString("About_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Repository.
        /// </summary>
        internal static string About_Github {
            get {
                return ResourceManager.GetString("About_Github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 1.0.0.
        /// </summary>
        internal static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply changes.
        /// </summary>
        internal static string btnApply {
            get {
                return ResourceManager.GetString("btnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Servers.
        /// </summary>
        internal static string BtnLoad {
            get {
                return ResourceManager.GetString("BtnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Ping.
        /// </summary>
        internal static string BtnRefreshPing {
            get {
                return ResourceManager.GetString("BtnRefreshPing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock All.
        /// </summary>
        internal static string BtnReset {
            get {
                return ResourceManager.GetString("BtnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Dark Mode.
        /// </summary>
        internal static string BtnSwitchToDark {
            get {
                return ResourceManager.GetString("BtnSwitchToDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Light Mode.
        /// </summary>
        internal static string BtnSwitchToLight {
            get {
                return ResourceManager.GetString("BtnSwitchToLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-refresh ping (every 5s).
        /// </summary>
        internal static string ChkAutoRefresh {
            get {
                return ResourceManager.GetString("ChkAutoRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        internal static string ColBlock {
            get {
                return ResourceManager.GetString("ColBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City/Region.
        /// </summary>
        internal static string ColCity {
            get {
                return ResourceManager.GetString("ColCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string ColFlag {
            get {
                return ResourceManager.GetString("ColFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        internal static string ColIP {
            get {
                return ResourceManager.GetString("ColIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping (ms).
        /// </summary>
        internal static string ColPing {
            get {
                return ResourceManager.GetString("ColPing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block all servers in {0}.
        /// </summary>
        internal static string CtxBlock {
            get {
                return ResourceManager.GetString("CtxBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock all servers in {0}.
        /// </summary>
        internal static string CtxUnblock {
            get {
                return ResourceManager.GetString("CtxUnblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Mode: {0}.
        /// </summary>
        internal static string LblCurrentMode {
            get {
                return ResourceManager.GetString("LblCurrentMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure you run as Administrator!.
        /// </summary>
        internal static string MsgAdminReq {
            get {
                return ResourceManager.GetString("MsgAdminReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done! Applied rules for {0} servers..
        /// </summary>
        internal static string MsgApplySuccess {
            get {
                return ResourceManager.GetString("MsgApplySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string MsgApplyTitle {
            get {
                return ResourceManager.GetString("MsgApplyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to unblock ALL servers?.
        /// </summary>
        internal static string MsgConfirmReset {
            get {
                return ResourceManager.GetString("MsgConfirmReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done! List downloaded..
        /// </summary>
        internal static string MsgDone {
            get {
                return ResourceManager.GetString("MsgDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        internal static string MsgDownloading {
            get {
                return ResourceManager.GetString("MsgDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MsgErrorTitle {
            get {
                return ResourceManager.GetString("MsgErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firewall Error: {0}.
        /// </summary>
        internal static string MsgFirewallError {
            get {
                return ResourceManager.GetString("MsgFirewallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rules deleted. You can play on any server now..
        /// </summary>
        internal static string MsgResetDone {
            get {
                return ResourceManager.GetString("MsgResetDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available! ({0}).
        /// </summary>
        internal static string MsgUpdateStatus {
            get {
                return ResourceManager.GetString("MsgUpdateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working....
        /// </summary>
        internal static string MsgWorking {
            get {
                return ResourceManager.GetString("MsgWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Settings_About {
            get {
                return ResourceManager.GetString("Settings_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Settings_General {
            get {
                return ResourceManager.GetString("Settings_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string TitleConfirm {
            get {
                return ResourceManager.GetString("TitleConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string TitleInfo {
            get {
                return ResourceManager.GetString("TitleInfo", resourceCulture);
            }
        }
    }
}
